-- 000016_replace_hobbies_with_interests.up.sql
--
-- Sustituye dos cosas a la vez por un único sistema de "intereses":
--   1. profiles.interests (TEXT[] libre de la 000003): texto suelto,
--      sin estructura, imposible de agregar ni de mostrar de forma
--      consistente ("¿esto es un hobby o una frase?").
--   2. hobby_definitions/profile_hobbies (000013): catálogo cerrado
--      donde TODO tenía intensidad 1-5, aunque muchos ítems concretos
--      (ej. "Guitarra", "Anime") no necesitan puntuarse, solo marcarse.
--
-- El reemplazo es un único catálogo con una bandera has_level por
-- ítem: unos se puntúan 1-5 (intereses amplios, "cuánto te gusta"),
-- otros son una simple etiqueta sí/no (intereses concretos, "lo tienes
-- o no"). Igual que en la 000013, la regla "has_level=false ⇒ level
-- NULL, has_level=true ⇒ level obligatorio" cruza dos tablas y no se
-- puede expresar como CHECK de Postgres — se aplica en
-- internal/profiles/service.go antes de escribir.

DROP TRIGGER IF EXISTS profile_hobbies_set_updated_at ON profile_hobbies;
DROP TABLE IF EXISTS profile_hobbies;
DROP TABLE IF EXISTS hobby_definitions;

ALTER TABLE profiles DROP COLUMN IF EXISTS interests;

CREATE TABLE interests (
    key         TEXT PRIMARY KEY,
    category    TEXT NOT NULL,
    label       TEXT NOT NULL,
    has_level   BOOLEAN NOT NULL,
    sort_order  SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE profile_interests (
    profile_id    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    interest_key  TEXT NOT NULL REFERENCES interests(key),
    level         SMALLINT CHECK (level BETWEEN 1 AND 5),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (profile_id, interest_key)
);

CREATE INDEX profile_interests_profile_id_idx ON profile_interests (profile_id);

CREATE TRIGGER profile_interests_set_updated_at
    BEFORE UPDATE ON profile_interests
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- Catálogo: 291 filas generadas a partir de la lista aportada por el
-- usuario. Ver generate_interests_seed.py (fuera del repo del backend,
-- solo se usó para producir este INSERT) si hace falta regenerarlo
-- tras añadir/quitar ítems.
-- Total de filas generadas: 291
INSERT INTO interests (key, category, label, has_level, sort_order) VALUES
    ('deporte_actividad_fisica', 'sport_activity', 'Deporte / actividad física', true, 1),
    ('fitness_gimnasio', 'sport_activity', 'Fitness / gimnasio', true, 2),
    ('running', 'sport_activity', 'Running', true, 3),
    ('ciclismo', 'sport_activity', 'Ciclismo', true, 4),
    ('senderismo_montana', 'sport_activity', 'Senderismo / montaña', true, 5),
    ('deportes_de_equipo', 'sport_activity', 'Deportes de equipo', true, 6),
    ('deportes_acuaticos', 'sport_activity', 'Deportes acuáticos', true, 7),
    ('deportes_de_invierno', 'sport_activity', 'Deportes de invierno', true, 8),
    ('deportes_de_combate', 'sport_activity', 'Deportes de combate', true, 9),
    ('atletismo', 'sport_activity', 'Atletismo', true, 10),
    ('baile', 'sport_activity', 'Baile', true, 11),
    ('yoga_pilates', 'sport_activity', 'Yoga / pilates', true, 12),
    ('equitacion', 'sport_activity', 'Equitación', true, 13),
    ('escalada', 'sport_activity', 'Escalada', true, 14),
    ('bricolaje_diy', 'creativity_manual', 'Bricolaje / DIY', true, 1),
    ('carpinteria', 'creativity_manual', 'Carpintería', true, 2),
    ('restauracion', 'creativity_manual', 'Restauración', true, 3),
    ('manualidades', 'creativity_manual', 'Manualidades', true, 4),
    ('artesania', 'creativity_manual', 'Artesanía', true, 5),
    ('costura', 'creativity_manual', 'Costura', true, 6),
    ('tejido_crochet', 'creativity_manual', 'Tejido / crochet', true, 7),
    ('jardineria', 'creativity_manual', 'Jardinería', true, 8),
    ('plantas_flores', 'creativity_manual', 'Plantas / flores', true, 9),
    ('decoracion_interiorismo', 'creativity_manual', 'Decoración / interiorismo', true, 10),
    ('fotografia', 'creativity_manual', 'Fotografía', true, 11),
    ('dibujo_pintura', 'creativity_manual', 'Dibujo / pintura', true, 12),
    ('escritura', 'creativity_manual', 'Escritura', true, 13),
    ('cocina', 'creativity_manual', 'Cocina', true, 14),
    ('reposteria', 'creativity_manual', 'Repostería', true, 15),
    ('lectura', 'culture_intellectual', 'Lectura', true, 1),
    ('ciencia', 'culture_intellectual', 'Ciencia', true, 2),
    ('tecnologia_informatica', 'culture_intellectual', 'Tecnología / informática', true, 3),
    ('programacion', 'culture_intellectual', 'Programación', true, 4),
    ('arte_y_cultura', 'culture_intellectual', 'Arte y cultura', true, 5),
    ('historia', 'culture_intellectual', 'Historia', true, 6),
    ('filosofia', 'culture_intellectual', 'Filosofía', true, 7),
    ('psicologia', 'culture_intellectual', 'Psicología', true, 8),
    ('aprendizaje_formacion', 'culture_intellectual', 'Aprendizaje / formación', true, 9),
    ('musica', 'culture_intellectual', 'Música', true, 10),
    ('cine_series', 'culture_intellectual', 'Cine / series', true, 11),
    ('teatro', 'culture_intellectual', 'Teatro', true, 12),
    ('videojuegos', 'leisure_entertainment', 'Videojuegos', true, 1),
    ('juegos_de_mesa', 'leisure_entertainment', 'Juegos de mesa', true, 2),
    ('juegos_de_cartas', 'leisure_entertainment', 'Juegos de cartas', true, 3),
    ('viajar', 'leisure_entertainment', 'Viajar', true, 4),
    ('naturaleza', 'leisure_entertainment', 'Naturaleza', true, 5),
    ('camping', 'leisure_entertainment', 'Camping', true, 6),
    ('excursiones', 'leisure_entertainment', 'Excursiones', true, 7),
    ('compras', 'leisure_entertainment', 'Compras', true, 8),
    ('salir_a_comer', 'leisure_entertainment', 'Salir a comer', true, 9),
    ('cafes', 'leisure_entertainment', 'Cafés', true, 10),
    ('vida_nocturna_clubs', 'leisure_entertainment', 'Vida nocturna / clubs', true, 11),
    ('fiestas', 'leisure_entertainment', 'Fiestas', true, 12),
    ('conciertos_festivales', 'leisure_entertainment', 'Conciertos / festivales', true, 13),
    ('socializar', 'leisure_entertainment', 'Socializar', true, 14),
    ('conocer_gente_nueva', 'leisure_entertainment', 'Conocer gente nueva', true, 15),
    ('actividades_con_amigos', 'leisure_entertainment', 'Actividades con amigos', true, 16),
    ('animales', 'lifestyle_other', 'Animales', true, 1),
    ('coches_motor', 'lifestyle_other', 'Coches / motor', true, 2),
    ('moda', 'lifestyle_other', 'Moda', true, 3),
    ('belleza_cosmetica', 'lifestyle_other', 'Belleza / cosmética', true, 4),
    ('bienestar', 'lifestyle_other', 'Bienestar', true, 5),
    ('meditacion', 'lifestyle_other', 'Meditación', true, 6),
    ('voluntariado', 'lifestyle_other', 'Voluntariado', true, 7),
    ('dibujo', 'art_creativity', 'Dibujo', false, 1),
    ('pintura', 'art_creativity', 'Pintura', false, 2),
    ('acuarela', 'art_creativity', 'Acuarela', false, 3),
    ('oleo', 'art_creativity', 'Óleo', false, 4),
    ('ilustracion', 'art_creativity', 'Ilustración', false, 5),
    ('escultura', 'art_creativity', 'Escultura', false, 6),
    ('fotografia_de_naturaleza', 'art_creativity', 'Fotografía de naturaleza', false, 7),
    ('fotografia_urbana', 'art_creativity', 'Fotografía urbana', false, 8),
    ('poesia', 'art_creativity', 'Poesía', false, 9),
    ('caligrafia', 'art_creativity', 'Caligrafía', false, 10),
    ('origami', 'art_creativity', 'Origami', false, 11),
    ('modelismo', 'art_creativity', 'Modelismo', false, 12),
    ('maquetas', 'art_creativity', 'Maquetas', false, 13),
    ('scrapbooking', 'art_creativity', 'Scrapbooking', false, 14),
    ('coleccionismo', 'art_creativity', 'Coleccionismo', false, 15),
    ('bricolaje', 'diy_crafts', 'Bricolaje', false, 1),
    ('restauracion_de_muebles', 'diy_crafts', 'Restauración de muebles', false, 2),
    ('electronica_diy', 'diy_crafts', 'Electrónica DIY', false, 3),
    ('impresion_3d', 'diy_crafts', 'Impresión 3D', false, 4),
    ('ceramica', 'diy_crafts', 'Cerámica', false, 5),
    ('bordado', 'diy_crafts', 'Bordado', false, 6),
    ('punto', 'diy_crafts', 'Punto', false, 7),
    ('crochet', 'diy_crafts', 'Crochet', false, 8),
    ('cuero', 'diy_crafts', 'Cuero', false, 9),
    ('fabricacion_de_velas', 'diy_crafts', 'Fabricación de velas', false, 10),
    ('fabricacion_de_jabon', 'diy_crafts', 'Fabricación de jabón', false, 11),
    ('reparaciones_domesticas', 'diy_crafts', 'Reparaciones domésticas', false, 12),
    ('cantar', 'music', 'Cantar', false, 1),
    ('karaoke', 'music', 'Karaoke', false, 2),
    ('guitarra', 'music', 'Guitarra', false, 3),
    ('guitarra_electrica', 'music', 'Guitarra eléctrica', false, 4),
    ('bajo', 'music', 'Bajo', false, 5),
    ('piano', 'music', 'Piano', false, 6),
    ('teclado', 'music', 'Teclado', false, 7),
    ('bateria', 'music', 'Batería', false, 8),
    ('violin', 'music', 'Violín', false, 9),
    ('violonchelo', 'music', 'Violonchelo', false, 10),
    ('saxofon', 'music', 'Saxofón', false, 11),
    ('flauta', 'music', 'Flauta', false, 12),
    ('otros_instrumentos', 'music', 'Otros instrumentos', false, 13),
    ('composicion_musical', 'music', 'Composición musical', false, 14),
    ('produccion_musical', 'music', 'Producción musical', false, 15),
    ('dj', 'music', 'DJ', false, 16),
    ('pop', 'music_genres', 'Pop', false, 1),
    ('rock', 'music_genres', 'Rock', false, 2),
    ('hard_rock', 'music_genres', 'Hard rock', false, 3),
    ('metal', 'music_genres', 'Metal', false, 4),
    ('punk', 'music_genres', 'Punk', false, 5),
    ('indie', 'music_genres', 'Indie', false, 6),
    ('alternative', 'music_genres', 'Alternative', false, 7),
    ('grunge', 'music_genres', 'Grunge', false, 8),
    ('electronica', 'music_genres', 'Electrónica', false, 9),
    ('techno', 'music_genres', 'Techno', false, 10),
    ('house', 'music_genres', 'House', false, 11),
    ('trance', 'music_genres', 'Trance', false, 12),
    ('edm', 'music_genres', 'EDM', false, 13),
    ('hip_hop', 'music_genres', 'Hip hop', false, 14),
    ('rap', 'music_genres', 'Rap', false, 15),
    ('r_b', 'music_genres', 'R&B', false, 16),
    ('soul', 'music_genres', 'Soul', false, 17),
    ('funk', 'music_genres', 'Funk', false, 18),
    ('reggae', 'music_genres', 'Reggae', false, 19),
    ('ska', 'music_genres', 'Ska', false, 20),
    ('jazz', 'music_genres', 'Jazz', false, 21),
    ('blues', 'music_genres', 'Blues', false, 22),
    ('musica_clasica', 'music_genres', 'Música clásica', false, 23),
    ('country', 'music_genres', 'Country', false, 24),
    ('folk', 'music_genres', 'Folk', false, 25),
    ('flamenco', 'music_genres', 'Flamenco', false, 26),
    ('musica_latina', 'music_genres', 'Música latina', false, 27),
    ('reggaeton', 'music_genres', 'Reggaeton', false, 28),
    ('salsa', 'music_genres', 'Salsa', false, 29),
    ('bachata', 'music_genres', 'Bachata', false, 30),
    ('tango', 'music_genres', 'Tango', false, 31),
    ('k_pop', 'music_genres', 'K-pop', false, 32),
    ('j_pop', 'music_genres', 'J-pop', false, 33),
    ('gospel', 'music_genres', 'Gospel', false, 34),
    ('bandas_sonoras', 'music_genres', 'Bandas sonoras', false, 35),
    ('pc_gaming', 'gaming_geek', 'PC gaming', false, 1),
    ('playstation', 'gaming_geek', 'PlayStation', false, 2),
    ('xbox', 'gaming_geek', 'Xbox', false, 3),
    ('nintendo', 'gaming_geek', 'Nintendo', false, 4),
    ('juegos_moviles', 'gaming_geek', 'Juegos móviles', false, 5),
    ('juegos_retro', 'gaming_geek', 'Juegos retro', false, 6),
    ('rpg', 'gaming_geek', 'RPG', false, 7),
    ('mmorpg', 'gaming_geek', 'MMORPG', false, 8),
    ('juegos_de_estrategia', 'gaming_geek', 'Juegos de estrategia', false, 9),
    ('juegos_de_simulacion', 'gaming_geek', 'Juegos de simulación', false, 10),
    ('dungeons_dragons', 'gaming_geek', 'Dungeons & Dragons', false, 11),
    ('anime', 'gaming_geek', 'Anime', false, 12),
    ('manga', 'gaming_geek', 'Manga', false, 13),
    ('cosplay', 'gaming_geek', 'Cosplay', false, 14),
    ('comics', 'gaming_geek', 'Cómics', false, 15),
    ('ciencia_ficcion', 'gaming_geek', 'Ciencia ficción', false, 16),
    ('fantasia', 'gaming_geek', 'Fantasía', false, 17),
    ('tecnologia', 'gaming_geek', 'Tecnología', false, 18),
    ('robotica', 'gaming_geek', 'Robótica', false, 19),
    ('inteligencia_artificial', 'gaming_geek', 'Inteligencia artificial', false, 20),
    ('futbol', 'sports_specific', 'Fútbol', false, 1),
    ('baloncesto', 'sports_specific', 'Baloncesto', false, 2),
    ('tenis', 'sports_specific', 'Tenis', false, 3),
    ('padel', 'sports_specific', 'Pádel', false, 4),
    ('voleibol', 'sports_specific', 'Voleibol', false, 5),
    ('badminton', 'sports_specific', 'Bádminton', false, 6),
    ('golf', 'sports_specific', 'Golf', false, 7),
    ('beisbol', 'sports_specific', 'Béisbol', false, 8),
    ('rugby', 'sports_specific', 'Rugby', false, 9),
    ('hockey', 'sports_specific', 'Hockey', false, 10),
    ('boxeo', 'sports_specific', 'Boxeo', false, 11),
    ('mma', 'sports_specific', 'MMA', false, 12),
    ('judo', 'sports_specific', 'Judo', false, 13),
    ('karate', 'sports_specific', 'Karate', false, 14),
    ('taekwondo', 'sports_specific', 'Taekwondo', false, 15),
    ('esqui', 'sports_specific', 'Esquí', false, 16),
    ('snowboard', 'sports_specific', 'Snowboard', false, 17),
    ('surf', 'sports_specific', 'Surf', false, 18),
    ('windsurf', 'sports_specific', 'Windsurf', false, 19),
    ('kitesurf', 'sports_specific', 'Kitesurf', false, 20),
    ('buceo', 'sports_specific', 'Buceo', false, 21),
    ('kayak', 'sports_specific', 'Kayak', false, 22),
    ('piraguismo', 'sports_specific', 'Piragüismo', false, 23),
    ('natacion', 'sports_specific', 'Natación', false, 24),
    ('triatlon', 'sports_specific', 'Triatlón', false, 25),
    ('gimnasia', 'sports_specific', 'Gimnasia', false, 26),
    ('patinaje', 'sports_specific', 'Patinaje', false, 27),
    ('mountain_bike', 'sports_specific', 'Mountain bike', false, 28),
    ('motociclismo', 'sports_specific', 'Motociclismo', false, 29),
    ('automovilismo', 'sports_specific', 'Automovilismo', false, 30),
    ('coches', 'motor', 'Coches', false, 1),
    ('motocicletas', 'motor', 'Motocicletas', false, 2),
    ('coches_clasicos', 'motor', 'Coches clásicos', false, 3),
    ('motos_clasicas', 'motor', 'Motos clásicas', false, 4),
    ('motorsport', 'motor', 'Motorsport', false, 5),
    ('mecanica', 'motor', 'Mecánica', false, 6),
    ('tuning', 'motor', 'Tuning', false, 7),
    ('restauracion_de_vehiculos', 'motor', 'Restauración de vehículos', false, 8),
    ('conduccion', 'motor', 'Conducción', false, 9),
    ('karting', 'motor', 'Karting', false, 10),
    ('perros', 'nature_animals', 'Perros', false, 1),
    ('gatos', 'nature_animals', 'Gatos', false, 2),
    ('caballos', 'nature_animals', 'Caballos', false, 3),
    ('pajaros', 'nature_animals', 'Pájaros', false, 4),
    ('peces_acuarios', 'nature_animals', 'Peces / acuarios', false, 5),
    ('reptiles', 'nature_animals', 'Reptiles', false, 6),
    ('roedores', 'nature_animals', 'Roedores', false, 7),
    ('animales_de_granja', 'nature_animals', 'Animales de granja', false, 8),
    ('apicultura', 'nature_animals', 'Apicultura', false, 9),
    ('pesca', 'nature_animals', 'Pesca', false, 10),
    ('observacion_de_aves', 'nature_animals', 'Observación de aves', false, 11),
    ('senderismo', 'nature_animals', 'Senderismo', false, 12),
    ('montanismo', 'nature_animals', 'Montañismo', false, 13),
    ('plantas', 'nature_animals', 'Plantas', false, 14),
    ('flores', 'nature_animals', 'Flores', false, 15),
    ('huerto', 'nature_animals', 'Huerto', false, 16),
    ('viajes', 'travel', 'Viajes', false, 1),
    ('escapadas_urbanas', 'travel', 'Escapadas urbanas', false, 2),
    ('viajes_de_naturaleza', 'travel', 'Viajes de naturaleza', false, 3),
    ('viajes_de_playa', 'travel', 'Viajes de playa', false, 4),
    ('viajes_de_montana', 'travel', 'Viajes de montaña', false, 5),
    ('road_trips', 'travel', 'Road trips', false, 6),
    ('mochilero_backpacking', 'travel', 'Mochilero / backpacking', false, 7),
    ('camper_autocaravana', 'travel', 'Camper / autocaravana', false, 8),
    ('cruceros', 'travel', 'Cruceros', false, 9),
    ('turismo_cultural', 'travel', 'Turismo cultural', false, 10),
    ('turismo_gastronomico', 'travel', 'Turismo gastronómico', false, 11),
    ('viajes_de_aventura', 'travel', 'Viajes de aventura', false, 12),
    ('viajes_de_lujo', 'travel', 'Viajes de lujo', false, 13),
    ('cocina_italiana', 'gastronomy', 'Cocina italiana', false, 1),
    ('cocina_espanola', 'gastronomy', 'Cocina española', false, 2),
    ('cocina_francesa', 'gastronomy', 'Cocina francesa', false, 3),
    ('cocina_griega', 'gastronomy', 'Cocina griega', false, 4),
    ('cocina_portuguesa', 'gastronomy', 'Cocina portuguesa', false, 5),
    ('cocina_mexicana', 'gastronomy', 'Cocina mexicana', false, 6),
    ('cocina_argentina', 'gastronomy', 'Cocina argentina', false, 7),
    ('cocina_brasilena', 'gastronomy', 'Cocina brasileña', false, 8),
    ('cocina_peruana', 'gastronomy', 'Cocina peruana', false, 9),
    ('cocina_colombiana', 'gastronomy', 'Cocina colombiana', false, 10),
    ('cocina_japonesa', 'gastronomy', 'Cocina japonesa', false, 11),
    ('cocina_china', 'gastronomy', 'Cocina china', false, 12),
    ('cocina_coreana', 'gastronomy', 'Cocina coreana', false, 13),
    ('cocina_tailandesa', 'gastronomy', 'Cocina tailandesa', false, 14),
    ('cocina_vietnamita', 'gastronomy', 'Cocina vietnamita', false, 15),
    ('cocina_india', 'gastronomy', 'Cocina india', false, 16),
    ('cocina_turca', 'gastronomy', 'Cocina turca', false, 17),
    ('cocina_arabe', 'gastronomy', 'Cocina árabe', false, 18),
    ('cocina_libanesa', 'gastronomy', 'Cocina libanesa', false, 19),
    ('cocina_marroqui', 'gastronomy', 'Cocina marroquí', false, 20),
    ('cocina_africana', 'gastronomy', 'Cocina africana', false, 21),
    ('sushi', 'gastronomy', 'Sushi', false, 22),
    ('barbacoa', 'gastronomy', 'Barbacoa', false, 23),
    ('street_food', 'gastronomy', 'Street food', false, 24),
    ('comida_picante', 'gastronomy', 'Comida picante', false, 25),
    ('marisco', 'gastronomy', 'Marisco', false, 26),
    ('pescado', 'gastronomy', 'Pescado', false, 27),
    ('carne', 'gastronomy', 'Carne', false, 28),
    ('dulces', 'gastronomy', 'Dulces', false, 29),
    ('postres', 'gastronomy', 'Postres', false, 30),
    ('comida_saludable', 'gastronomy', 'Comida saludable', false, 31),
    ('comida_vegetariana', 'gastronomy', 'Comida vegetariana', false, 32),
    ('comida_vegana', 'gastronomy', 'Comida vegana', false, 33),
    ('accion', 'film_entertainment', 'Acción', false, 1),
    ('aventuras', 'film_entertainment', 'Aventuras', false, 2),
    ('comedia', 'film_entertainment', 'Comedia', false, 3),
    ('drama', 'film_entertainment', 'Drama', false, 4),
    ('romance_film', 'film_entertainment', 'Romance', false, 5),
    ('thriller_film', 'film_entertainment', 'Thriller', false, 6),
    ('terror_film', 'film_entertainment', 'Terror', false, 7),
    ('ciencia_ficcion_film', 'film_entertainment', 'Ciencia ficción', false, 8),
    ('fantasia_film', 'film_entertainment', 'Fantasía', false, 9),
    ('misterio_film', 'film_entertainment', 'Misterio', false, 10),
    ('crimen', 'film_entertainment', 'Crimen', false, 11),
    ('documentales', 'film_entertainment', 'Documentales', false, 12),
    ('animacion', 'film_entertainment', 'Animación', false, 13),
    ('guerra', 'film_entertainment', 'Guerra', false, 14),
    ('musicales', 'film_entertainment', 'Musicales', false, 15),
    ('western', 'film_entertainment', 'Western', false, 16),
    ('reality', 'film_entertainment', 'Reality', false, 17),
    ('novelas', 'books', 'Novelas', false, 1),
    ('romance_book', 'books', 'Romance', false, 2),
    ('thriller_book', 'books', 'Thriller', false, 3),
    ('misterio_book', 'books', 'Misterio', false, 4),
    ('fantasia_book', 'books', 'Fantasía', false, 5),
    ('ciencia_ficcion_book', 'books', 'Ciencia ficción', false, 6),
    ('terror_book', 'books', 'Terror', false, 7),
    ('biografias', 'books', 'Biografías', false, 8),
    ('negocios', 'books', 'Negocios', false, 9),
    ('desarrollo_personal', 'books', 'Desarrollo personal', false, 10);
